### ISSUE TITLE
console error about "signatures:enable-checking?"

### ISSUE THREAD

**Issue by gus-massa** [racket/deinprogramm#4]
When I try to run any program in DrRacket with the DeinProgramm language I get an error in the console:

    "preferences:get: tried to get a preference but no default set for 'signatures:enable-checking?"

I guess the problem is in https://github.com/racket/deinprogramm/blob/4529dcc379dd92b765b575dc2e171cf1ba3793a0/deinprogramm/deinprogramm/deinprogramm-langs.rkt#L213

Perhaps the problem is that I have most of the time most of the tools disabled, and I just enabled DeinProgramm.

**Comment by mikesperber** [comment]
This has languished for a long time now. I'm not sure how you produced this error - could you post a recipe, @gus-massa?

**Comment by gus-massa** [comment]
After playing for a while, I think the problem is when you try to run a program in "DeinProgram" with the "Signatures" tool disable.

I should get a clean machine to be sure, but let's hope this fake steps are good enough.

1) Open DrRackt
2) Go to the menu Edit>Preference go to the tab Tools
3) Disable all tools (except Slideshow, IIRC it's something bad happens if you disable Slideshow)
Then reenable "DeinProgram" but keep "Signatures" disabled
4) Press Ok to confirm, exit DrRacket and reopen DrRacket (so only some tools are loaded)
5) Select the language "DeinProgram" and run a program 

Alternative

3) Just disable "Signatures" instead of disabling all the tools.

**Comment by rfindler** [comment]
This suggests that DeinProgramm should check if the other tool is off and
give a message to the user and disable itself if it doesn't find it.

It would be nice if DrR supported declaring such dependencies too, of
course. But maybe the simple thing is best done first?

Robby

**Comment by mikesperber** [comment]
Finally got around to fixing this. (No need to disable the DeinProgramm tool.) Sorry for taking so long!
