### ISSUE TITLE
DeinProgramm appears twice in DrRacket tools configuration

### ISSUE THREAD

**Issue by spdegabrielle** [racket/deinprogramm#5]
![image](https://user-images.githubusercontent.com/108047/83190448-57165080-a12a-11ea-822b-77dc341166b5.png)
DeinProgramm appears twice.

**Comment by spdegabrielle** [comment]
Both tools have the same name
https://github.com/racket/deinprogramm/blob/master/deinprogramm/deinprogramm/info.rkt#L8

**Comment by spdegabrielle** [comment]
@mikesperber gentle nudge :)

**Comment by mikesperber** [comment]
@spdegabrielle Sorry - for some reason, I never see the first-time git notifications for racket.

**Comment by spdegabrielle** [comment]
No problem. Thank you.
